### ISSUE TITLE
Class 'Apipack\Apipack\Facades\Google' not found

### ISSUE THREAD

**Issue by Ehesp** [krissanawat/laravel-4-apipack#1]
'Apipack\Eden\EdenServiceProvider' 
'Google'  => 'Apipack\Apipack\Facades\Google'

These have been added to the app.php file.

When declaring "$auth = Google::auth(...)" I get the error:

Class 'Apipack\Apipack\Facades\Google' not found.

Should be Facade not be 'Apipack\Eden\Facade\Google'? I've no idea, I changed that and get the error:

Class 'Apipack\Eden\Eden_Google' not found

Edit: composer dump-autoload has also been tried.

**Comment by krissanawat** [comment]
Now it's work for me because composer dump-autoload it's don't work 
I reinstall package and autoload class map & autoload namespace it's appear list of apipack

**Comment by Ehesp** [comment]
Could you tell me which files to auto load in the composer.json file? Or just paste the code/json which I need to use, since I'm not sure how to autoload namespaces?

**Comment by krissanawat** [comment]
you try to check /vendor/composer/autoload_classmap.php this is picture after remove and reinstall package
![screenclip](https://f.cloud.github.com/assets/2133223/803594/aa1adce0-edf6-11e2-92b7-4fc920037819.png)

**Comment by Ehesp** [comment]
Seems to be working now, thanks for updating.
