### ISSUE TITLE
Class 'Apipack\Eden\DOMDocument' not found

### ISSUE THREAD

**Issue by Ehesp** [krissanawat/laravel-4-apipack#2]
Can't make a pull request on this environment, so will make a issue for it.

In the file "vendor/apipack/eden/src/Apipack/Eden/google/base.php" you've declared a namespace of "namespace Apipack\Eden;".

The issue is that you're creating a DOMDocument object twice in this file (lines 182 and 255).  So when either of the parent methods are called, Laravel searches for the class "Apipack\Eden\DOMDocument", which obviously doesn't exist.

To overcome this, change:

new DOMDocument();
to:
new \DOMDocument(); 

This way, the namespace is escaped, and thus it loads the PHP DOMDocument class as it should :)

I think this is correct, I'm not pro so please correct me, but it's working here.  However I'd imagine this is the case with other files as well.

**Comment by krissanawat** [comment]
thank, now I fix it 
cheer
